In [ ]:
# I'm going to combine all of the .xyz files we want along with their associated data labels
# The geometries of every state and transition state are in "gaussian_vicinal_wb97xd_tzvp_f321g"
# What we want to use is the geometries in "silanols_vicinal"
# there are 388 xyz geometries to go with each entry in the rates csv files
# rates_dft is the rates calculated from DFT (these are supposed to be sampled, so I'm not sure why they did all of them, maybe for accuracy verification?)
# rates_ml is the rates predicted by the algorithm mentioned in the earlier part of the paper. This is what we will use

# the rcat column in the csv file seems to be what they did unsupervized learning on, although I am not completely sure how this was calculated
# my best guess is arrhenius eqn at 400 deg C but I haven't found anything to prove that

# I reckon we do rcat since it is the most interesting and we only have so many figures but I will include the others in the dataset too

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import pandas as pd

In [ ]:
labeldf = pd.read_csv("/content/drive/MyDrive/rates_ml.csv") # this filepath will be different for everyone depending on location, adjust if needed

In [ ]:
labeldf.head()

index                  name         k2        K1        rAC       rcat  \
0      0  coords_1Kps_001_0001   4154.248  0.358224   1127.679   1127.664   
1      1  coords_1Kps_002_0002   7842.454  0.174889   1207.018   1207.000   
2      2  coords_1Kps_002_0103   9576.523  1.026440   4944.847   4944.548   
3      3  coords_1Kps_003_0003  59065.000  0.553494  21580.010  21574.300   
4      4  coords_1Kps_003_0102   2904.114  0.938815   1434.774   1434.749   

    kg(473K)       kg(673K)      kg(873K)  pg(473K)  pg(673K)  pg(873K)  \
0  17.990870   63998.070000  5.905110e+06  1.000000       1.0       1.0   
1  60.892890  162649.600000  1.291530e+07  1.000000       1.0       1.0   
2   0.000005       1.538175  1.559147e+03  0.018377       1.0       1.0   
3  22.120010   82010.950000  7.720031e+06  1.000000       1.0       1.0   
4  50.705310  138567.900000  1.108968e+07  1.000000       1.0       1.0   

   reff(Tg=473K)  reff(Tg=673K)  reff(Tg=873K)  
0     1127.66400       1127.664       1127.664  
1     1207.00000       1207.000       1207.000  
2       90.86669       4944.548       4944.548  
3    21574.30000      21574.300      21574.300  
4     1434.74900       1434.749       1434.749

In [ ]:
folder_path = "/content/drive/MyDrive/silanols_vicinal" # make path name string a variable if someone else runs this they would have to input the folder from the SI in their drive's location

# Get a list of all files in the folder
file_list = os.listdir(folder_path)
print(file_list)
print(len(file_list))

['coords_1Kps_001_0001.xyz', 'coords_1Kps_002_0002.xyz', 'coords_1Kps_002_0103.xyz', 'coords_1Kps_003_0003.xyz', 'coords_1Kps_003_0102.xyz', 'coords_1Kps_004_0204.xyz', 'coords_1Kps_004_0105.xyz', 'coords_1Kps_004_0306.xyz', 'coords_1Kps_004_0007.xyz', 'coords_1Kps_005_0001.xyz', 'coords_1Kps_006_0407.xyz', 'coords_1Kps_006_0203.xyz', 'coords_1Kps_007_0005.xyz', 'coords_1Kps_007_0102.xyz', 'coords_1Kps_007_0709.xyz', 'coords_1Kps_007_0408.xyz', 'coords_1Kps_007_0306.xyz', 'coords_1Kps_008_0203.xyz', 'coords_1Kps_008_0405.xyz', 'coords_1Kps_008_0001.xyz', 'coords_1Kps_009_0008.xyz', 'coords_1Kps_009_0408.xyz', 'coords_1Kps_009_0103.xyz', 'coords_1Kps_009_0506.xyz', 'coords_1Kps_009_0002.xyz', 'coords_1Kps_010_0212.xyz', 'coords_1Kps_010_0506.xyz', 'coords_1Kps_010_0813.xyz', 'coords_1Kps_010_0001.xyz', 'coords_1Kps_010_0911.xyz', 'coords_1Kps_010_0410.xyz', 'coords_1Kps_010_0307.xyz', 'coords_1Kps_011_0001.xyz', 'coords_1Kps_011_0304.xyz', 'coords_1Kps_011_0506.xyz', 'coords_1Kps_011_02

In [ ]:
pip install xyz-py

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 40.7 MB/s eta 0:00:00


In [ ]:
import xyz_py as xyzp

In [ ]:
help(xyzp.load_xyz)

Help on function load_xyz in module xyz_py.xyz_py:

load_xyz(f_name: str, atomic_numbers: bool = False, add_indices: bool = False, capitalise: bool = True, check: bool = True, missing_headers: bool = False) -> tuple[list, numpy.ndarray[typing.Any, numpy.dtype[+_ScalarType_co]]]
    Load labels and coordinates from a .xyz file



    File assumes two header lines, first containing number of atoms

    and second containing a comment or blank, followed by actual data

    Parameters
    ----------
    f_name: str
        File name
    atomic_numbers: bool, default False
        If True, reads xyz file with atomic numbers and converts to labels
    add_indices: bool, default False
        If True, add indices to atomic labels

        (replacing those which may exist already)
    capitalise: bool, default True
        If True, capitalise atomic labels
    check: bool, default True
        If True, check xyz file before loading
    missing_headers: bool, default False
        If True, then

In [ ]:
test_coords = xyzp.load_xyz("/content/drive/MyDrive/silanols_vicinal/coords_1Kps_001_0001.xyz") # oh yeah that's awesome, good package

In [ ]:
print(test_coords[0])
print(test_coords[1])
print(test_coords[1][0])

['F', 'F', 'F', 'F', 'Si', 'Si', 'O', 'O', 'O', 'H', 'H']
[[-2.11975178  1.50069892 -0.36361168]
 [-2.37533734 -1.23103682 -0.71987053]
 [ 2.33552808 -1.32539002 -0.55981726]
 [ 1.99841315  1.25144317 -0.89070369]
 [-1.58748406  0.          0.        ]
 [ 1.58748406  0.          0.        ]
 [-0.01888556 -0.18871356 -0.28932679]
 [-1.82068638 -0.21080748  1.69100683]
 [ 1.79733515  0.21080748  1.69318366]
 [-2.71579025 -0.44376802  1.90780634]
 [ 1.2033109  -0.3244406   2.20618875]]
[-2.11975178  1.50069892 -0.36361168]


In [ ]:
# make a list to iterate over and eventually add to dataframe

coord_list = []

index = 0 # manually make index for the loop
for filename in file_list:
    file_path = os.path.join(folder_path, filename)
    loop_coords = xyzp.load_xyz(file_path) # load in xyz file in the format seen above 11x3 array of atoms and xyz coords

    coord_list.append(loop_coords) # append list

    index += 1 # add one to index for the next loop to use

In [ ]:
print(coord_list[0][0])
print('________')
print(coord_list[0][1])
# note, logs of the kinetic constants were used (nevermind not for the unsupervised learning part)
print('________')
print(coord_list[0][1][0])

['F', 'F', 'F', 'F', 'Si', 'Si', 'O', 'O', 'O', 'H', 'H']
________
[[-2.11975178  1.50069892 -0.36361168]
 [-2.37533734 -1.23103682 -0.71987053]
 [ 2.33552808 -1.32539002 -0.55981726]
 [ 1.99841315  1.25144317 -0.89070369]
 [-1.58748406  0.          0.        ]
 [ 1.58748406  0.          0.        ]
 [-0.01888556 -0.18871356 -0.28932679]
 [-1.82068638 -0.21080748  1.69100683]
 [ 1.79733515  0.21080748  1.69318366]
 [-2.71579025 -0.44376802  1.90780634]
 [ 1.2033109  -0.3244406   2.20618875]]
________
[-2.11975178  1.50069892 -0.36361168]


In [ ]:
def r1r2(F1,F2,F3,F4):
    #F1-4 are xyz coords
    # I'm looking at these from a top down view i.e. OH groups facing out of the screen
    # F1 is the top left, it's the first F [-2.11975178  1.50069892 -0.36361168]
    # F2 is the next one. bottom left [-2.37533734 -1.23103682 -0.71987053]
    # F3 is the next, bottom right [ 2.33552808 -1.32539002 -0.55981726]
    # F4 is the next, top right [ 1.99841315  1.25144317 -0.89070369]
    r1 = np.linalg.norm(F1-F2)
    r2 = np.linalg.norm(F3-F4) #order doesn't matter here F1 or F2 first it is under sqrt

    #also find the midpoint of the two radii
    r1_mid = np.array([(F1[0]+F2[0])/2,(F1[1]+F2[1])/2,(F1[2]+F2[2])/2])
    r2_mid = np.array([(F3[0]+F4[0])/2,(F3[1]+F4[1])/2,(F3[2]+F4[2])/2])
    return r1,r2,r1_mid,r2_mid

In [ ]:
def shaft(r1_mid,r2_mid):
    shaft_len = np.linalg.norm(r1_mid-r2_mid)
    return shaft_len

In [ ]:
def thetas(F1,r1_mid,F4,r2_mid):
    u1 = F1-r1_mid # vector facing up r1 from midpoint
    v1 = r2_mid-r1_mid # vector facing to the right from r1midpoint to r2midpoint

    # we only want the theta in the xy plane so remove the z coord
    u1 = u1[0:2]
    v1 = v1[0:2]

    theta1 = np.arccos(np.dot(u1,v1)/(np.linalg.norm(u1)*np.linalg.norm(v1))) # formula for angle between vectors

    u2 = F4-r2_mid # vector facing up r2 from midpoint
    v2 = r1_mid-r2_mid # vector facing to the right from r2midpoint to r1midpoint

    # we only want the theta in the xy plane so remove the z coord
    u2 = u2[0:2]
    v2 = v2[0:2]

    theta2 = np.arccos(np.dot(u2,v2)/(np.linalg.norm(u2)*np.linalg.norm(v2))) # formula for angle between vectors

    return theta1,theta2

In [ ]:
def torsion_funx(F4,r2_mid,F1,r1_mid):
    top = F4-r2_mid
    bottom = F1-r1_mid

    # removing coordinate similar to what was done for theta, now we only want the angle in the yz plane so remove x

    top = top[1:3]
    bottom = bottom[1:3]

    torsion = np.arccos(np.dot(top,bottom)/(np.linalg.norm(top)*np.linalg.norm(bottom)))
    return torsion

In [ ]:
len(coord_list)

388

In [ ]:
# finally make a function that spits out 6 lists and loops over every thing in the coord_list
def lists_out(coord_list):

    # Initialize lists
    rplus_list = []
    rminus_list = []
    shaft_list = []
    thetaplus_list = []
    thetaminus_list = []
    torsion_list = []

    for j in range(len(coord_list)):
        # define fluorine atom coords for j index
        F1,F2,F3,F4 = coord_list[j][1][0],coord_list[j][1][1],coord_list[j][1][2],coord_list[j][1][3]

        # find radii
        r1,r2,r1_mid,r2_mid = r1r2(F1,F2,F3,F4)

        # calculate r+ and r- as done in paper
        rplus = r1+r2
        rminus = r1-r2

        # find shaft length
        shaft_len = shaft(r1_mid,r2_mid)

        # find thetas
        theta1,theta2 = thetas(F1,r1_mid,F4,r2_mid)
        # convert units
        theta1 = np.rad2deg(theta1)
        theta2 = np.rad2deg(theta2)

        # calculate theta+ and theta-
        thetaplus = theta1+theta2
        thetaminus = theta1-theta2

        # find torsion
        torsion = torsion_funx(F4,r2_mid,F1,r1_mid)
        # convert units
        torsion = np.rad2deg(torsion)

        # now add all of these to the list at j spot
        rplus_list.append(rplus)
        rminus_list.append(rminus)
        shaft_list.append(shaft_len)
        thetaplus_list.append(thetaplus)
        thetaminus_list.append(thetaminus)
        torsion_list.append(torsion)
    # spit the lists out

    return rplus_list,rminus_list,shaft_list,thetaplus_list,thetaminus_list,torsion_list


In [ ]:
rplus_list,rminus_list,shaft_list,thetaplus_list,thetaminus_list,torsion_list = lists_out(coord_list)

In [ ]:
# make new df
outputdf = labeldf.copy()

outputdf['r1'] = rplus_list
outputdf['r2'] = rminus_list
outputdf['shaft_length'] = shaft_list
outputdf['theta1'] = thetaplus_list
outputdf['theta2'] = thetaminus_list
outputdf['torsion'] = torsion_list

In [ ]:
outputdf.head(400)

index                  name            k2        K1           rAC  \
0        0  coords_1Kps_001_0001  4.154248e+03  0.358224  1.127679e+03   
1        1  coords_1Kps_002_0002  7.842454e+03  0.174889  1.207018e+03   
2        2  coords_1Kps_002_0103  9.576523e+03  1.026440  4.944847e+03   
3        3  coords_1Kps_003_0003  5.906500e+04  0.553494  2.158001e+04   
4        4  coords_1Kps_003_0102  2.904114e+03  0.938815  1.434774e+03   
..     ...                   ...           ...       ...           ...   
383    383  coords_1Kps_099_0102  1.630037e+05  0.716986  6.963183e+04   
384    384  coords_1Kps_099_0406  7.200909e+04  1.001387  3.673744e+04   
385    385  coords_1Kps_099_0507  5.594144e+03  0.014340  8.221265e+01   
386    386  coords_1Kps_100_0103  2.651290e+08  0.201686  4.597372e+07   
387    387  coords_1Kps_100_0405  5.366895e+03  2.078260  3.669385e+03   

             rcat      kg(473K)       kg(673K)      kg(873K)      pg(473K)  \
0    1.127664e+03  1.799087e+01   63998.070000  5.905110e+06  1.000000e+00   
1    1.207000e+03  6.089289e+01  162649.600000  1.291530e+07  1.000000e+00   
2    4.944548e+03  5.152252e-06       1.538175  1.559147e+03  1.837715e-02   
3    2.157430e+04  2.212001e+01   82010.950000  7.720031e+06  1.000000e+00   
4    1.434749e+03  5.070531e+01  138567.900000  1.108968e+07  1.000000e+00   
..            ...           ...            ...           ...           ...   
383  6.957246e+04  9.829145e-02    1782.579000  3.977919e+05  1.000000e+00   
384  3.672090e+04  5.784885e+00   33583.320000  4.042024e+06  1.000000e+00   
385  8.221257e+01  1.550250e+01   61374.920000  5.960255e+06  1.000000e+00   
386  2.940699e+07  9.027036e-15       0.000001  2.864705e-02  3.249733e-11   
387  3.669220e+03  1.033276e-04      15.667250  1.051841e+04  3.106315e-01   

     ...  pg(873K)  reff(Tg=473K)  reff(Tg=673K)  reff(Tg=873K)        r1  \
0    ...       1.0    1127.664000     1127.66400   1.127664e+03  5.386470   
1    ...       1.0    1207.000000     1207.00000   1.207000e+03  5.480156   
2    ...       1.0      90.866690     4944.54800   4.944548e+03  5.411764   
3    ...       1.0   21574.300000    21574.30000   2.157430e+04  5.382705   
4    ...       1.0    1434.749000     1434.74900   1.434749e+03  5.110214   
..   ...       ...            ...            ...            ...       ...   
383  ...       1.0   69572.460000    69572.46000   6.957246e+04  5.183443   
384  ...       1.0   36720.900000    36720.90000   3.672090e+04  5.226315   
385  ...       1.0      82.212570       82.21257   8.221257e+01  5.390237   
386  ...       1.0       0.000956   115987.60000   2.940699e+07  5.273317   
387  ...       1.0    1139.776000     3669.22000   3.669220e+03  5.047953   

           r2  shaft_length      theta1     theta2    torsion  
0    0.146928      4.421667  167.201469   6.565717  14.747488  
1    0.025942      4.482822  185.517513   6.196532  11.304056  
2    0.122305      3.959733  166.709309  -6.711944   1.613101  
3   -0.132749      4.302871  146.813691   0.724178  27.109136  
4   -0.099353      4.520485  164.223536  -0.614341   3.085213  
..        ...           ...         ...        ...        ...  
383  0.146010      4.252750  133.708083 -15.449385  36.586584  
384  0.040849      3.963426  149.838518  11.807033   9.469350  
385  0.027154      4.369727  165.445006  -1.752052  43.830134  
386  0.104830      4.111392  208.624227  15.114690  34.892059  
387 -0.101910      3.998843  150.438018  42.619980  54.582465  

[388 rows x 21 columns]

In [ ]:
outputdf.to_csv('data_with_features.csv', index=False)