In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# random ideas
# narrowing down regimes where certain features have a greater impact on reactivity
# maybe split up PCA graph into two sections and seeing if a more defnitive feature pops out, or if explained variance increases for both splits
# then you can sort of identify two regimes by which bonds are changing maybe
# maybe assuming symmetry between the two Si centers is an alright assumption
# having a probability 3D probability density of mass change with axes
# calculate position of atoms of interest if they are in fact definitively defined by the F coords

# The paper states that it at least qualitatively looks like the sticky outyness of the central O bond between the two Sis
# and how much the outward facing oxygen bonds point away from eachother (I think of this as how wide the W shape of the structure is)

# How can we make features to include at least one (ideally both) of these changes in the features
# this would allow for the principal components to have interpretable units as it will be a combination of these geometrically understood features
# Getting the two outward oxygen angles is somewhat easy

# could be just having all the angles of each Si tetrahedron
# Actually I reckon this wouldn't work too well, both less and more reactive sites seem to have a 90 deg angle, but the two 90 deg angles are more tilted relative to eachother

# an alternative to the above could be

# could also be the distance between every atom, with the two O2s included

# I am noticing now that the most reactive site has the central O between the two Sis pointed in the same direction as the hydrogens (relative to the Sis I guess)
# maybe this and other features could be captured by some metric that measures the similarity between two vector's direction

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
import sys
import pandas as pd

In [ ]:
labeldf = pd.read_csv("/content/drive/MyDrive/rates_ml.csv") # adjust so that the file path is right, this will be different for different people

In [ ]:
labeldf.head()

index                  name         k2        K1        rAC       rcat  \
0      0  coords_1Kps_001_0001   4154.248  0.358224   1127.679   1127.664   
1      1  coords_1Kps_002_0002   7842.454  0.174889   1207.018   1207.000   
2      2  coords_1Kps_002_0103   9576.523  1.026440   4944.847   4944.548   
3      3  coords_1Kps_003_0003  59065.000  0.553494  21580.010  21574.300   
4      4  coords_1Kps_003_0102   2904.114  0.938815   1434.774   1434.749   

    kg(473K)       kg(673K)      kg(873K)  pg(473K)  pg(673K)  pg(873K)  \
0  17.990870   63998.070000  5.905110e+06  1.000000       1.0       1.0   
1  60.892890  162649.600000  1.291530e+07  1.000000       1.0       1.0   
2   0.000005       1.538175  1.559147e+03  0.018377       1.0       1.0   
3  22.120010   82010.950000  7.720031e+06  1.000000       1.0       1.0   
4  50.705310  138567.900000  1.108968e+07  1.000000       1.0       1.0   

   reff(Tg=473K)  reff(Tg=673K)  reff(Tg=873K)  
0     1127.66400       1127.664       1127.664  
1     1207.00000       1207.000       1207.000  
2       90.86669       4944.548       4944.548  
3    21574.30000      21574.300      21574.300  
4     1434.74900       1434.749       1434.749

In [ ]:
folder_path = "/content/drive/MyDrive/silanols_vicinal" # make path name string a variable if someone else runs this they would have to input the folder from the SI in their drive's location

# Get a list of all files in the folder
file_list = os.listdir(folder_path)
print(file_list)
print(len(file_list))

['coords_1Kps_001_0001.xyz', 'coords_1Kps_002_0002.xyz', 'coords_1Kps_002_0103.xyz', 'coords_1Kps_003_0003.xyz', 'coords_1Kps_003_0102.xyz', 'coords_1Kps_004_0204.xyz', 'coords_1Kps_004_0105.xyz', 'coords_1Kps_004_0306.xyz', 'coords_1Kps_004_0007.xyz', 'coords_1Kps_005_0001.xyz', 'coords_1Kps_006_0407.xyz', 'coords_1Kps_006_0203.xyz', 'coords_1Kps_007_0005.xyz', 'coords_1Kps_007_0102.xyz', 'coords_1Kps_007_0709.xyz', 'coords_1Kps_007_0408.xyz', 'coords_1Kps_007_0306.xyz', 'coords_1Kps_008_0203.xyz', 'coords_1Kps_008_0405.xyz', 'coords_1Kps_008_0001.xyz', 'coords_1Kps_009_0008.xyz', 'coords_1Kps_009_0408.xyz', 'coords_1Kps_009_0103.xyz', 'coords_1Kps_009_0506.xyz', 'coords_1Kps_009_0002.xyz', 'coords_1Kps_010_0212.xyz', 'coords_1Kps_010_0506.xyz', 'coords_1Kps_010_0813.xyz', 'coords_1Kps_010_0001.xyz', 'coords_1Kps_010_0911.xyz', 'coords_1Kps_010_0410.xyz', 'coords_1Kps_010_0307.xyz', 'coords_1Kps_011_0001.xyz', 'coords_1Kps_011_0304.xyz', 'coords_1Kps_011_0506.xyz', 'coords_1Kps_011_02

In [ ]:
pip install xyz-py

   ╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.1/2.9 MB 8.0 MB/s eta 0:00:01
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 77fd0e609bd3868006d4bb3bb95cdc4081d9e292ac84f6c9fb564b5751d2689e
             Got        09fabf8900571ee19c126c7ca6b5df528710b7da92774ae9742285f3b9a12d64



In [ ]:
pip install xyz_py

  Using cached xyz_py-5.19.2-py3-none-any.whl.metadata (1.6 kB)
  Using cached ase-3.26.0-py3-none-any.whl.metadata (4.1 kB)
Using cached xyz_py-5.19.2-py3-none-any.whl (32 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 49.2 MB/s eta 0:00:00


In [ ]:
import xyz_py as xyzp

In [ ]:
help(xyzp.load_xyz)

Help on function load_xyz in module xyz_py.xyz_py:

load_xyz(f_name: str, atomic_numbers: bool = False, add_indices: bool = False, capitalise: bool = True, check: bool = True, missing_headers: bool = False) -> tuple[list, numpy.ndarray[typing.Any, numpy.dtype[+_ScalarType_co]]]
    Load labels and coordinates from a .xyz file



    File assumes two header lines, first containing number of atoms

    and second containing a comment or blank, followed by actual data

    Parameters
    ----------
    f_name: str
        File name
    atomic_numbers: bool, default False
        If True, reads xyz file with atomic numbers and converts to labels
    add_indices: bool, default False
        If True, add indices to atomic labels

        (replacing those which may exist already)
    capitalise: bool, default True
        If True, capitalise atomic labels
    check: bool, default True
        If True, check xyz file before loading
    missing_headers: bool, default False
        If True, then

In [ ]:
test_coords = xyzp.load_xyz("/content/drive/MyDrive/silanols_vicinal/coords_1Kps_001_0001.xyz") # oh yeah that's awesome, good package

In [ ]:
print(test_coords[0])
print(test_coords[1])
print(test_coords[1][0])

['F', 'F', 'F', 'F', 'Si', 'Si', 'O', 'O', 'O', 'H', 'H']
[[-2.11975178  1.50069892 -0.36361168]
 [-2.37533734 -1.23103682 -0.71987053]
 [ 2.33552808 -1.32539002 -0.55981726]
 [ 1.99841315  1.25144317 -0.89070369]
 [-1.58748406  0.          0.        ]
 [ 1.58748406  0.          0.        ]
 [-0.01888556 -0.18871356 -0.28932679]
 [-1.82068638 -0.21080748  1.69100683]
 [ 1.79733515  0.21080748  1.69318366]
 [-2.71579025 -0.44376802  1.90780634]
 [ 1.2033109  -0.3244406   2.20618875]]
[-2.11975178  1.50069892 -0.36361168]


In [ ]:
# make a list to iterate over and eventually add to dataframe

coord_list = []

index = 0 # manually make index for the loop
for filename in file_list:
    file_path = os.path.join(folder_path, filename)
    loop_coords = xyzp.load_xyz(file_path) # load in xyz file in the format seen above 11x3 array of atoms and xyz coords

    coord_list.append(loop_coords) # append list

    index += 1 # add one to index for the next loop to use

In [ ]:
print(coord_list[0][0])
print('________')
print(coord_list[0][1])
# note, logs of the kinetic constants were used
print('________')
print(coord_list[0][1][0])

['F', 'F', 'F', 'F', 'Si', 'Si', 'O', 'O', 'O', 'H', 'H']
________
[[-2.11975178  1.50069892 -0.36361168]
 [-2.37533734 -1.23103682 -0.71987053]
 [ 2.33552808 -1.32539002 -0.55981726]
 [ 1.99841315  1.25144317 -0.89070369]
 [-1.58748406  0.          0.        ]
 [ 1.58748406  0.          0.        ]
 [-0.01888556 -0.18871356 -0.28932679]
 [-1.82068638 -0.21080748  1.69100683]
 [ 1.79733515  0.21080748  1.69318366]
 [-2.71579025 -0.44376802  1.90780634]
 [ 1.2033109  -0.3244406   2.20618875]]
________
[-2.11975178  1.50069892 -0.36361168]


In [ ]:
# ['F', 'F', 'F', 'F', 'Si', 'Si', 'O', 'O', 'O', 'H', 'H']
# first Si in the negative direction (left) is Si1
# first O is the center O
# 2nd and 3rd O is the left and right O attached to the Si respectively

# left is negative x and right is positive x, looking at the xz plane with y going into the screen

def W_angle(Si1,Si2,Out1,Out2):

    # inputs come in as lists so change to arrays so addition can be done
    Si1 = np.array(Si1)
    Si2 = np.array(Si2)
    Out1 = np.array(Out1)
    Out2 = np.array(Out2)

    u1 = Out1-Si1 # vector facing up to Sticking out atom from left Si
    v1 = Si2-Si1 # vector facing to the right from Si1 to Si2

    theta1 = np.arccos(np.dot(u1,v1)/(np.linalg.norm(u1)*np.linalg.norm(v1))) # formula for angle between vectors

    u2 = Out2-Si2 # vector facing up to Sticking out atom from right Si
    v2 = Si1-Si2 # vector facing to the right from Si1 to Si2

    theta2 = np.arccos(np.dot(u2,v2)/(np.linalg.norm(u2)*np.linalg.norm(v2))) # formula for angle between vectors

    theta_plus = theta1+theta2
    theta_minus = theta1 - theta2

    # both of these thetas should be taken with vectors projected onto the same plane like they were in the normal featurization.
    # but this is good enough

    # now get ratios of radii of sticking out atoms
    len1 = np.linalg.norm(u1) # left radii

    len2 = np.linalg.norm(u2) # right radii

    len_plus = len1 + len2
    len_minus = len1 - len2

    # don't necessarily need radii of distance between the Sis as this is specified in the CenterO features

    # now calculating torsion between the two sticking out atoms and the Sis

    top = Out2-Si2
    bottom = Out1-Si1

    # only consider the yz plane, eliminate the x

    top = top[1:3]
    bottom = bottom[1:3]

    torsion = np.arccos(np.dot(top,bottom)/(np.linalg.norm(top)*np.linalg.norm(bottom)))

    return theta_plus,theta_minus,torsion

# ['F', 'F', 'F', 'F', 'Si', 'Si', 'O', 'O', 'O', 'H', 'H']
# first Si in the negative direction (left) is Si1
# first O is the center O
# 2nd and 3rd O is the left and right O attached to the Si respectively

# left is negative x and right is positive x, looking at the xz plane with y going into the screen

def W_lens(Si1,Si2,Out1,Out2):

    # inputs come in as list so change to arrays

    Si1 = np.array(Si1)
    Si2 = np.array(Si2)
    Out1 = np.array(Out1)
    Out2 = np.array(Out2)

    r1 = Out1-Si1 # vector facing up to Sticking out atom from left Si
    r2 = Out2-Si2 # vector facing to the right from Si1 to Si2

    # calculate ratios

    len1 = np.linalg.norm(r1) # left radii

    len2 = np.linalg.norm(r2) # right radii

    len_plus = len1 + len2
    len_minus = len1 - len2

    return len_plus,len_minus

def all_W_angles(some_row):

    F1a,F1b,F2b,F2a,centerO,O1,O2,Si1,Si2,H1,H2 = some_row # unpack the input list

    # input is just every row, spits out list of:
    # theta plus minus and torsion, then plus and minus lengths, for each group of atoms that form a W
    # in the order Fas, Fbs, Os

    list_to_append = list(W_angle(Si1,Si2,F1a,F2a))
    list_to_append.extend(list(W_lens(Si1,Si2,F1a,F2a)))
    list_to_append.extend(list(W_angle(Si1,Si2,F1b,F2b)))
    list_to_append.extend(list(W_lens(Si1,Si2,F1b,F2b)))
    list_to_append.extend(list(W_angle(Si1,Si2,O1,O2)))
    list_to_append.extend(list(W_lens(Si1,Si2,O1,O2)))


    return list_to_append

In [ ]:
def centerO_funx(some_row):

    F1a,F1b,F2b,F2a,centerO,O1,O2,Si1,Si2,H1,H2 = some_row # unpack the input list

    # inputs come in as list so change to arrays

    centerO = np.array(centerO)
    Si1 = np.array(Si1)
    Si2 = np.array(Si2)
    O1 = np.array(O1)
    O2 = np.array(O2)

    # recalculate outward facing vectors for O1 and O2
    OutO_1_vec = O1 - Si1
    OutO_2_vec = O2 - Si2

    l_vec_OG = Si1 - centerO # vector facing from center O to left Si
    r_vec_OG = Si2 - centerO # vector facing from center O to right Si

    # get lengths of bonds and calculate ratio
    l_len = np.linalg.norm(l_vec_OG)
    r_len = np.linalg.norm(r_vec_OG)

    center_r_plus = l_len + r_len
    center_r_minus = l_len - r_len

    # only want the components in the zx plane
    l_vec = np.array([l_vec_OG[0],l_vec_OG[2]])
    r_vec = np.array([r_vec_OG[0],r_vec_OG[2]])

    # now find torsion angles respective to each silicon out Oxygen
    # only in zy plane so get rid of x
    OutO_1_vec = OutO_1_vec[1:3]
    OutO_2_vec = OutO_2_vec[1:3]
    l_vec = l_vec_OG[1:3]
    r_vec = r_vec_OG[1:3]

    torsion1 = np.arccos(np.dot(OutO_1_vec,l_vec)/(np.linalg.norm(OutO_1_vec)*np.linalg.norm(l_vec)))

    torsion2 = np.arccos(np.dot(OutO_2_vec,r_vec)/(np.linalg.norm(OutO_2_vec)*np.linalg.norm(r_vec)))

    # had some issues with the term inside the arccos part being -1.00000002 and causing a nan due to being out of range of the arccos function
    # making this to enforce the proper value of the arcos of -1 being pi and not nan

    if np.isnan(torsion1) == True:
        torsion1 = np.pi
    if np.isnan(torsion2) == True:
        torsion2 = np.pi

    # use addition and difference of features like the original paper thetas
    torsion_plus = torsion1 + torsion2
    torsion_minus = torsion1 - torsion2

    # need vector between the two Sis only in zx plane
    Si_vec = Si2 - Si1
    Si_vec = np.array([Si_vec[0],Si_vec[2]])

    # only using the left angle fo this featurization because it shouldnt matter both sides will have the same information on the stickyoutyness of the center O
    center_phi = np.arccos(np.dot(l_vec,Si_vec)/(np.linalg.norm(l_vec)*np.linalg.norm(Si_vec)))

    # now calculate the h*cosine(phi) to get stickyoutness
    stickyouty = l_len*np.cos(center_phi)

    return torsion_plus,torsion_minus,stickyouty,center_r_plus,center_r_minus


In [ ]:
len(coord_list)

388

In [ ]:
# finally make a function that spits out feature dataframe and loops over every thing in the coord_list
def lists_out(coord_list):

    # Initialize dataframe

    feature_df = pd.DataFrame()

    # inialize CenterO funx lists

    torsion_plus_list = []
    torsion_minus_list = []
    stickyouty_list = []
    center_r_plus_list = []
    center_r_minus_list = []

    # initialize the W lists for each pair of atoms

    Fa_theta_plus_list = []
    Fa_theta_minus_list = []
    Fa_torsion_list = []
    Fa_len_plus_list = []
    Fa_len_minus_list = []

    Fb_theta_plus_list = []
    Fb_theta_minus_list = []
    Fb_torsion_list = []
    Fb_len_plus_list = []
    Fb_len_minus_list = []

    O_theta_plus_list = []
    O_theta_minus_list = []
    O_torsion_list = []
    O_len_plus_list = []
    O_len_minus_list = []

    for j in range(len(coord_list)):

        #flatten array at the row to a list of lists since this is what the functions I made take as an input
        current_row = coord_list[j][1].tolist()

        output_list = all_W_angles(current_row)
        # I wish I had done this in a less strange way but oh well
        Fa_theta_plus_list.append(output_list[0])
        Fa_theta_minus_list.append(output_list[1])
        Fa_torsion_list.append(output_list[2])
        Fa_len_plus_list.append(output_list[3])
        Fa_len_minus_list.append(output_list[4])

        Fb_theta_plus_list.append(output_list[5])
        Fb_theta_minus_list.append(output_list[6])
        Fb_torsion_list.append(output_list[7])
        Fb_len_plus_list.append(output_list[8])
        Fb_len_minus_list.append(output_list[9])

        O_theta_plus_list.append(output_list[10])
        O_theta_minus_list.append(output_list[11])
        O_torsion_list.append(output_list[12])
        O_len_plus_list.append(output_list[13])
        O_len_minus_list.append(output_list[14])

        # now just do this for center O and output and fix inevitable bugs

        center_O_output = centerO_funx(current_row)

        # put output into lists

        torsion_plus_list.append(center_O_output[0])
        torsion_minus_list.append(center_O_output[1])
        stickyouty_list.append(center_O_output[2])
        center_r_plus_list.append(center_O_output[3])
        center_r_minus_list.append(center_O_output[4])

    # turn lists into dataframe
    feature_df['Fa_theta_plus'] = Fa_theta_plus_list
    feature_df['Fa_theta_minus'] = Fa_theta_minus_list
    feature_df['Fa_torsion'] = Fa_torsion_list
    feature_df['Fa_len_plus'] = Fa_len_plus_list
    feature_df['Fa_len_minus'] = Fa_len_minus_list

    feature_df['Fb_theta_plus'] = Fb_theta_plus_list
    feature_df['Fb_theta_minus'] = Fb_theta_minus_list
    feature_df['Fb_torsion'] = Fb_torsion_list
    feature_df['Fb_len_plus'] = Fb_len_plus_list
    feature_df['Fb_len_minus'] = Fb_len_minus_list

    feature_df['O_theta_plus'] = O_theta_plus_list
    feature_df['O_theta_minus'] = O_theta_minus_list
    feature_df['O_torsion'] = O_torsion_list
    feature_df['O_len_plus'] = O_len_plus_list
    feature_df['O_len_minus'] = O_len_minus_list

    feature_df['center_torsion_plus'] = torsion_plus_list
    feature_df['center_torsion_minus'] = torsion_minus_list
    feature_df['center_height'] = stickyouty_list # the sticky outy height
    feature_df['center_r_plus'] = center_r_plus_list
    feature_df['center_r_minus'] = center_r_minus_list

    return feature_df


In [ ]:
print(len(coord_list[0][1].tolist()))

11


In [ ]:
feature_df = lists_out(coord_list)

/tmp/ipython-input-568794414.py:38: RuntimeWarning: invalid value encountered in arccos
  torsion1 = np.arccos(np.dot(OutO_1_vec,l_vec)/(np.linalg.norm(OutO_1_vec)*np.linalg.norm(l_vec)))


In [ ]:
feature_df.head(100)

Fa_theta_plus  Fa_theta_minus  Fa_torsion  Fa_len_plus  Fa_len_minus  \
0        3.293172       -0.077100    0.311678     5.483570     -0.102064   
1        3.842869        0.363175    0.232807     5.402661     -0.065523   
2        2.832844       -0.138224    0.105074     5.386619      0.045142   
3        2.965641        0.432033    0.500611     5.438158      0.024400   
4        3.154948        0.054604    0.099346     5.320945     -0.057706   
..            ...             ...         ...          ...           ...   
95       3.507833        0.085072    0.264309     5.224980     -0.117034   
96       2.927415        0.011366    0.442854     5.360398      0.017602   
97       3.791569        0.268760    0.392687     5.341990     -0.085460   
98       2.694160       -0.004829    0.104967     5.469942      0.199545   
99       3.777086       -0.021574    0.122843     5.541995      0.115495   

    Fb_theta_plus  Fb_theta_minus  Fb_torsion  Fb_len_plus  Fb_len_minus  \
0        3.523059        0.125022    0.198111     5.455464     -0.103517   
1        3.764248       -0.216311    0.315246     5.157857     -0.007258   
2        3.071761        0.067012    0.037984     5.489241     -0.132949   
3        3.524934       -0.116356    0.468631     5.375639      0.139081   
4        3.412771       -0.037349    0.067255     5.461579      0.024318   
..            ...             ...         ...          ...           ...   
95       3.388656       -0.202534    0.303434     5.575411      0.052836   
96       2.876519       -0.146753    0.499415     5.394544     -0.009191   
97       3.478868       -0.347763    0.385577     5.539685      0.014850   
98       2.754835        0.046003    0.273564     5.401540      0.076497   
99       3.272229        0.216919    0.110613     5.319221      0.031878   

    O_theta_plus  O_theta_minus  O_torsion  O_len_plus  O_len_minus  \
0       1.284863      -0.358128   0.322883    6.528657     1.092253   
1       1.541221      -0.504524   0.303247    6.136772     0.464089   
2       1.004226      -0.209584   0.271315    6.843151     1.462100   
3       1.212959      -0.299621   0.254058    6.432922     1.037949   
4       1.098932      -0.270457   0.043525    6.704263     1.366985   
..           ...            ...        ...         ...          ...   
95      1.276854      -0.351413   0.334863    6.442748     1.274158   
96      0.869811      -0.108592   0.609906    6.725365     1.704219   
97      1.381580      -0.400601   0.332102    6.238746     0.999429   
98      0.744719      -0.079913   0.391534    7.097773     1.564004   
99      1.377873      -0.372275   0.062948    6.348773     0.836448   

    center_torsion_plus  center_torsion_minus  center_theta  center_r_plus  \
0              6.208192              0.074993     -0.211745       5.510534   
1              6.270120              0.013066      0.207564       5.049563   
2              6.137602              0.145583     -0.080094       5.796059   
3              6.086755              0.196430      0.345823       5.705212   
4              6.240064              0.043121      0.066389       5.704681   
..                  ...                   ...           ...            ...   
95             6.279219              0.003967      0.302757       5.490886   
96             6.217265              0.065920      0.516907       5.748546   
97             6.271215              0.011971      0.274853       5.277316   
98             6.190699              0.092487     -0.271230       6.055323   
99             6.132542              0.150643     -0.083778       5.515252   

    center_r_minus  
0        -2.070577  
1        -1.629590  
2        -2.415823  
3        -2.224856  
4        -2.290114  
..             ...  
95       -2.020646  
96       -2.338914  
97       -1.877913  
98       -2.624474  
99       -2.022723  

[100 rows x 20 columns]

In [ ]:
feature_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Fa_theta_plus         388 non-null    float64
 1   Fa_theta_minus        388 non-null    float64
 2   Fa_torsion            388 non-null    float64
 3   Fa_len_plus           388 non-null    float64
 4   Fa_len_minus          388 non-null    float64
 5   Fb_theta_plus         388 non-null    float64
 6   Fb_theta_minus        388 non-null    float64
 7   Fb_torsion            388 non-null    float64
 8   Fb_len_plus           388 non-null    float64
 9   Fb_len_minus          388 non-null    float64
 10  O_theta_plus          388 non-null    float64
 11  O_theta_minus         388 non-null    float64
 12  O_torsion             388 non-null    float64
 13  O_len_plus            388 non-null    float64
 14  O_len_minus           388 non-null    float64
 15  center_torsion_plus   3

In [ ]:
data_with_features3 = pd.concat([labeldf, feature_df], axis=1)

In [ ]:
pd.set_option('display.max_columns', None)
data_with_features3.head()

index                  name         k2        K1        rAC       rcat  \
0      0  coords_1Kps_001_0001   4154.248  0.358224   1127.679   1127.664   
1      1  coords_1Kps_002_0002   7842.454  0.174889   1207.018   1207.000   
2      2  coords_1Kps_002_0103   9576.523  1.026440   4944.847   4944.548   
3      3  coords_1Kps_003_0003  59065.000  0.553494  21580.010  21574.300   
4      4  coords_1Kps_003_0102   2904.114  0.938815   1434.774   1434.749   

    kg(473K)       kg(673K)      kg(873K)  pg(473K)  pg(673K)  pg(873K)  \
0  17.990870   63998.070000  5.905110e+06  1.000000       1.0       1.0   
1  60.892890  162649.600000  1.291530e+07  1.000000       1.0       1.0   
2   0.000005       1.538175  1.559147e+03  0.018377       1.0       1.0   
3  22.120010   82010.950000  7.720031e+06  1.000000       1.0       1.0   
4  50.705310  138567.900000  1.108968e+07  1.000000       1.0       1.0   

   reff(Tg=473K)  reff(Tg=673K)  reff(Tg=873K)  Fa_theta_plus  Fa_theta_minus  \
0     1127.66400       1127.664       1127.664       3.293172       -0.077100   
1     1207.00000       1207.000       1207.000       3.842869        0.363175   
2       90.86669       4944.548       4944.548       2.832844       -0.138224   
3    21574.30000      21574.300      21574.300       2.965641        0.432033   
4     1434.74900       1434.749       1434.749       3.154948        0.054604   

   Fa_torsion  Fa_len_plus  Fa_len_minus  Fb_theta_plus  Fb_theta_minus  \
0    0.311678     5.483570     -0.102064       3.523059        0.125022   
1    0.232807     5.402661     -0.065523       3.764248       -0.216311   
2    0.105074     5.386619      0.045142       3.071761        0.067012   
3    0.500611     5.438158      0.024400       3.524934       -0.116356   
4    0.099346     5.320945     -0.057706       3.412771       -0.037349   

   Fb_torsion  Fb_len_plus  Fb_len_minus  O_theta_plus  O_theta_minus  \
0    0.198111     5.455464     -0.103517      1.284863      -0.358128   
1    0.315246     5.157857     -0.007258      1.541221      -0.504524   
2    0.037984     5.489241     -0.132949      1.004226      -0.209584   
3    0.468631     5.375639      0.139081      1.212959      -0.299621   
4    0.067255     5.461579      0.024318      1.098932      -0.270457   

   O_torsion  O_len_plus  O_len_minus  center_torsion_plus  \
0   0.322883    6.528657     1.092253             6.208192   
1   0.303247    6.136772     0.464089             6.270120   
2   0.271315    6.843151     1.462100             6.137602   
3   0.254058    6.432922     1.037949             6.086755   
4   0.043525    6.704263     1.366985             6.240064   

   center_torsion_minus  center_theta  center_r_plus  center_r_minus  
0              0.074993     -0.211745       5.510534       -2.070577  
1              0.013066      0.207564       5.049563       -1.629590  
2              0.145583     -0.080094       5.796059       -2.415823  
3              0.196430      0.345823       5.705212       -2.224856  
4              0.043121      0.066389       5.704681       -2.290114

In [ ]:
data_with_features3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 35 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 388 non-null    int64  
 1   name                  388 non-null    object 
 2   k2                    388 non-null    float64
 3   K1                    388 non-null    float64
 4   rAC                   388 non-null    float64
 5   rcat                  388 non-null    float64
 6   kg(473K)              388 non-null    float64
 7   kg(673K)              388 non-null    float64
 8   kg(873K)              388 non-null    float64
 9   pg(473K)              388 non-null    float64
 10  pg(673K)              388 non-null    float64
 11  pg(873K)              388 non-null    float64
 12  reff(Tg=473K)         388 non-null    float64
 13  reff(Tg=673K)         388 non-null    float64
 14  reff(Tg=873K)         388 non-null    float64
 15  Fa_theta_plus         3

In [ ]:
data_with_features3.to_csv('data_with_features3.csv', index=False)